### ISSUE TITLE
separate production and development branches

### ISSUE THREAD

**Issue by AunSyedShah** [umair313/flask-random-password-generatro#1]
production and development branches should be separated

**Comment by umair313** [comment]
in the case of different branches for production and development, every time in case of a change in dev then have to merge with production when there will be other files which are not part of development may cause issues.
am I right?

**Comment by umair313** [comment]
Created the Release version. that's recommended instead of creating different branches.

**Comment by AunSyedShah** [comment]
> in the case of different branches for production and development, every time in case of a change in dev then have to merge with production when there will be other files which are not part of development may cause issues. am I right?

This is better
